using System;
using System.Collections.Generic;
using System.Reflection;
using System.IO;
using System.Threading;

namespace locgen.CodeGen
{
	/// <summary>
	/// A C# code generator.
	/// </summary>
	internal sealed class CsharpCodeGenerator : LocCodeGenerator
	{
		#region data
		#endregion

		#region interface

		public CsharpCodeGenerator()
			: base("Csharp")
		{
		}

		#endregion

		#region LocCodeGenerator

		protected override void GenerateInternal(ILocTree data, StreamWriter file, CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			WriteFileHeader(file);
			cancellationToken.ThrowIfCancellationRequested();
		}

		#endregion

		#region implementation

		private void WriteFileHeader(StreamWriter file)
		{
			file.WriteLine("// <auto-generated>");
			file.WriteLine($"// Do not edit. Content of this file has been generated with locgen on {DateTime.Now.ToString(@"MM\/dd\/yyyy HH:mm")}.");
			file.WriteLine("// </auto-generated>");
		}

		#endregion
	}
}
