using System;
using System.Collections.Generic;
using System.Reflection;
using System.IO;
using System.Threading;

namespace locgen.CodeGen
{
	/// <summary>
	/// A C# code generator.
	/// </summary>
	internal sealed class CsharpCodeGenerator : LocCodeGenerator
	{
		#region data
		#endregion

		#region interface

		public CsharpCodeGenerator()
			: base("Csharp")
		{
		}

		#endregion

		#region LocCodeGenerator

		protected override void GenerateInternal(ILocTree data, StreamWriter file, CancellationToken cancellationToken)
		{
			WriteFileHeader(file, cancellationToken);
			WriteData(file, data, cancellationToken);
		}

		#endregion

		#region implementation

		private void WriteFileHeader(StreamWriter file, CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();

			file.WriteLine("// <auto-generated>");
			file.WriteLine($"// Do not edit. Content of this file has been generated with locgen on {DateTime.Now.ToString(@"yyyy\/MM\/dd HH:mm")}.");
			file.WriteLine("// </auto-generated>");
		}

		private void WriteData(StreamWriter file, ILocTree data, CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();

			file.WriteLine("using System;");
			file.WriteLine("using System.Resources;");
			file.WriteLine();

			if (string.IsNullOrEmpty(TargetNamespace))
			{
				WriteLocTree(file, data, cancellationToken, 0);
			}
			else
			{
				file.WriteLine("namespace " + TargetNamespace);
				file.WriteLine('{');
				WriteLocTree(file, data, cancellationToken, 1);
				file.WriteLine('}');
			}
		}

		private void WriteLocTree(StreamWriter file, ILocTree tree, CancellationToken cancellationToken, int identLevel)
		{
			cancellationToken.ThrowIfCancellationRequested();

			WriteLocNotes(file, tree, identLevel);
			WriteIdent(file, identLevel, "public partial class " + tree.Name);
			WriteIdent(file, identLevel, "{");

			WriteIdent(file, identLevel + 1, $"private readonly {ResourceManagerClassName} _resourceManager;");
			file.WriteLine();
			WriteIdent(file, identLevel + 1, $"public {tree.Name}({ResourceManagerClassName} resourceManager) {{ _resourceManager = resourceManager; }}");
			file.WriteLine();

			WriteLocGroupContent(file, tree, cancellationToken, identLevel + 1);
			WriteIdent(file, identLevel, "}");

			if (GenerateLocKeys)
			{
				file.WriteLine();

				WriteLocNotes(file, tree, identLevel);
				WriteIdent(file, identLevel, "public static class " + tree.Name + "Keys");
				WriteIdent(file, identLevel, "{");
				WriteLocGroupContentKeys(file, tree, cancellationToken, identLevel + 1);
				WriteIdent(file, identLevel, "}");
			}
		}

		private void WriteLocGroupContent(StreamWriter file, ILocTreeGroup group, CancellationToken cancellationToken, int identLevel)
		{
			cancellationToken.ThrowIfCancellationRequested();

			foreach (var item in group.Groups)
			{
				WriteLocGroup(file, item, cancellationToken, identLevel);
				file.WriteLine();
			}

			foreach (var item in group.Units)
			{
				WriteLocUnit(file, item, cancellationToken, identLevel);
				file.WriteLine();
			}
		}

		private void WriteLocGroupContentKeys(StreamWriter file, ILocTreeGroup group, CancellationToken cancellationToken, int identLevel)
		{
			cancellationToken.ThrowIfCancellationRequested();

			foreach (var item in group.Groups)
			{
				WriteLocGroupKeys(file, item, cancellationToken, identLevel);
				file.WriteLine();
			}

			foreach (var item in group.Units)
			{
				WriteLocUnitKeys(file, item, cancellationToken, identLevel);
				file.WriteLine();
			}
		}

		private void WriteLocGroup(StreamWriter file, ILocTreeGroup group, CancellationToken cancellationToken, int identLevel)
		{
			var groupClassName = GetGroupClassName(group.Name);

			cancellationToken.ThrowIfCancellationRequested();

			WriteIdent(file, identLevel, $"public struct {groupClassName}");
			WriteIdent(file, identLevel, "{");

			WriteIdent(file, identLevel + 1, $"private readonly {ResourceManagerClassName} _resourceManager;");
			file.WriteLine();
			WriteIdent(file, identLevel + 1, $"internal {groupClassName}({ResourceManagerClassName} resourceManager) {{ _resourceManager = resourceManager; }}");
			file.WriteLine();

			WriteLocGroupContent(file, group, cancellationToken, identLevel + 1);
			WriteIdent(file, identLevel, "}");
			file.WriteLine();

			WriteLocNotes(file, group, identLevel);
			WriteIdent(file, identLevel, $"public {groupClassName} {group.Name} {{ get {{ return new {groupClassName}(_resourceManager); }} }}");
		}

		private void WriteLocGroupKeys(StreamWriter file, ILocTreeGroup group, CancellationToken cancellationToken, int identLevel)
		{
			cancellationToken.ThrowIfCancellationRequested();

			WriteLocNotes(file, group, identLevel);
			WriteIdent(file, identLevel, $"public static class {group.Name}");
			WriteIdent(file, identLevel, "{");

			WriteLocGroupContentKeys(file, group, cancellationToken, identLevel + 1);
			WriteIdent(file, identLevel, "}");
		}

		private void WriteLocUnit(StreamWriter file, ILocTreeUnit unit, CancellationToken cancellationToken, int identLevel)
		{
			cancellationToken.ThrowIfCancellationRequested();

			WriteLocNotes(file, unit, identLevel);
			WriteIdent(file, identLevel, $"public string {unit.Name} {{ get {{ return _resourceManager.{ResourceManagerGetStringMethodName}(\"{unit.Id}\"); }} }}");
		}

		private void WriteLocUnitKeys(StreamWriter file, ILocTreeUnit unit, CancellationToken cancellationToken, int identLevel)
		{
			cancellationToken.ThrowIfCancellationRequested();

			WriteLocNotes(file, unit, identLevel);
			WriteIdent(file, identLevel, $"public const string {unit.Name}Key = \"{unit.Id}\";");
		}

		private void WriteLocNotes(StreamWriter file, ILocTreeItem item, int identLevel)
		{
			WriteIdent(file, identLevel, "/// <summary>");

			if (string.IsNullOrEmpty(item.Notes))
			{
				WriteIdent(file, identLevel, "/// ");
			}
			else
			{
				foreach (var line in item.Notes.Split(new char[] { '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries))
				{
					WriteIdent(file, identLevel, "/// " + line);
				}
			}

			WriteIdent(file, identLevel, "/// </summary>");
		}

		private static string GetGroupClassName(string groupName)
		{
			return '_' + groupName + "_Proxy";
		}

		#endregion
	}
}
